Development
Joyan11/RabonaKick pull request #1
Opened 2021-04-01 08:05 UTC by Joyan11

I've done the basic functionalities of the ecommerce app.
i would really appreciate a code review on this.

Note : class is used in ionicons tag because className dosent work for this set of icon provider in react

2021-05-08 05:43 UTC, tuhindas30 reviewed
Hey @Joyan11,
I had gone through your code. It is greatly written. I loved the way how you made apis for each operation. Each and every line looks neat and clean. However, some very small nitty changes that I would suggest and it's okay to keep it like this also.
* `faker` and `react-uuid` packages can be removed as the backend is involved.
* I think the `manifest.json` file is of no use. It can also be removed.
Once again this looks great. I learned a lot from your code. Keep going!

2021-05-09 07:41 UTC, shraddha319 commented
Hi Joyan,

Great work on this project! Neat code. I liked how modular your code base is. Most core functionalities have been broken down into separate components. One suggestion would be to include an index file in the components folder. You can export all the components into this file. This way when you're trying to use the components, you can import them from a single location. This would reduce the number of import statements and make it easier to understand.

2021-05-23 04:01 UTC, Joyan11 commented
> Hi Joyan,
> 
> Great work on this project! Neat code. I liked how modular your code base is. Most core functionalities have been broken down into separate components. One suggestion would be to include an index file in the components folder. You can export all the components into this file. This way when you're trying to use the components, you can import them from a single location. This would reduce the number of import statements and make it easier to understand.

hello,
Thank you very much for the review. I made the following changes in the code. this was a very useful suggestion , imports look a lot more organized now

2021-05-23 04:02 UTC, Joyan11 commented
> Hey @Joyan11,
> I had gone through your code. It is greatly written. I loved the way how you made apis for each operation. Each and every line looks neat and clean. However, some very small nitty changes that I would suggest and it's okay to keep it like this also.
> 
> * `faker` and `react-uuid` packages can be removed as the backend is involved.
> * I think the `manifest.json` file is of no use. It can also be removed.
>   Once again this looks great. I learned a lot from your code. Keep going!

Hello, 
Thanks for the review. I've removed the unwanted packages. Cheers!

2021-06-05 05:59 UTC, renukapaturkar requested changes
Hi Joyan, 
Your code is very well written and files are properly structured and modular. I have mentioned a small change to optimize code and avoid repetition and please make sure to remove all the `console.log()` and commented code once you are development is done.

I have leant a lot from this code review, Thank you.

2021-06-05 05:59 UTC, renukapaturkar commented on src/App.js
> +          <Route path="/signup" element={<Signup />}></Route>
Keep the`<Route></Route>` as `<Route/>`

2021-06-05 05:59 UTC, renukapaturkar commented on src/api/cart/removeFromCart.js
> +      { headers: { authorization: token } }
Try to put the common authorization header for all in a single function or  you can use axios interceptors. 
To know more about this check [here](https://axios-http.com/docs/config_defaults)

2021-09-06 09:06 UTC, closed without merging